In [1]:
import torch
from torch import nn
import math
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np

real = np.load('/content/drive/MyDrive/Footprints Datasets/real.npz')
fake = np.load('/content/drive/MyDrive/Footprints Datasets/fake.npz')

In [4]:
fake

NpzFile '/content/drive/MyDrive/Footprints Datasets/fake.npz' with keys: x, y

In [5]:
real.files
real['y'].shape


(750, 496)

In [6]:
real['x'].shape

(750, 1998, 101)

In [7]:
fake['x'].shape

(750, 1998, 101)

In [8]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 4

NameError: name 'transforms' is not defined

In [18]:
print(real['x'][2][728])

[2.3680e+04 3.2576e+04        inf 5.0848e+04 4.3280e+03 1.6288e+02
 1.0450e+02 8.6188e+01 1.9094e+01 1.2742e+01 1.5025e+02 9.2400e+02
 1.4210e+03 4.8675e+02 1.8156e+01 1.2050e+02 3.2650e+02 5.8550e+02
 5.1100e+02 1.3300e+02 5.0812e+01 5.6156e+01 2.0662e+02 4.0025e+02
 5.9500e+02 9.9300e+02 9.2450e+02 4.4375e+02 6.4625e+01 1.8016e+01
 3.2844e+01 6.0281e+01 5.4188e+01 6.5062e+01 1.4047e+01 6.5391e+00
 4.2688e+01 7.7000e+01 1.9594e+01 1.9873e-01 2.4648e+00 1.8496e+00
 3.0312e+00 7.0264e-01 1.3574e+00 1.4180e+00 9.9170e-01 4.6143e-01
 1.8398e+00 3.6367e+00 4.3384e-01 8.7939e-01 2.3652e+00 1.1475e+00
 5.1562e+00 1.6904e+00 1.0068e+00 7.1973e-01 2.0972e-01 1.1563e-05
 1.9019e-01 2.1692e-01 2.2949e-01 7.1472e-02 6.5491e-02 3.0005e-01
 2.0728e-01 1.1279e-01 4.5319e-02 3.1860e-01 3.4375e-01 2.8735e-01
 3.8794e-01 5.9277e-01 2.9388e-02 1.4001e-01 1.3391e-01 9.0918e-01
 7.6025e-01 1.1749e-01 2.9590e-01 7.9346e-01 2.9590e-01 8.5449e-02
 1.6699e-01 6.2256e-02 1.4107e-02 4.9164e-02 4.9377e-02 2.3682

In [ ]:
# prompt: take the real['y'] and return for every entry a tuple consisting the index of the first and last occurence of one and store in a new numpy array called modifiied_y

import numpy as np
modified_y = np.zeros((real['y'].shape[0], 2))
for i in range(real['y'].shape[0]):
  index_first = np.where(real['y'][i] == 1)[0][0]
  index_last = np.where(real['y'][i] == 1)[0][-1]
  modified_y[i] = [index_first, index_last]

print(modified_y[0])


[122. 220.]


In [ ]:
fake_sample = fake['y'][0]

print(np.unique(fake['y']))

[0]


In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])


In [19]:
# prompt: write a CNN model with 1 CNN layer, 1 max pooling, 1 CNN, 1 dense layer and an output of 496 nodes using tensorflow keras

import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.models import Model

# Define the input layer
inputs = Input(shape=(real['x'].shape[1], real['x'].shape[2], 1))

# Add the first CNN layer
conv1 = Conv2D(filters=16, kernel_size=3, activation='relu')(inputs)

# Add the max pooling layer
pool1 = MaxPooling2D(pool_size=2)(conv1)

# Add the second CNN layer
conv2 = Conv2D(filters=32, kernel_size=4, activation='relu')(pool1)

# Add the max pooling layer
pool2 = MaxPooling2D(pool_size=3)(conv2)

# Add the second CNN layer
conv3 = Conv2D(filters=64, kernel_size=4, activation='relu')(pool2)

# Add the max pooling layer
pool3 = MaxPooling2D(pool_size=3)(conv3)

# Flatten the output of the CNN layers
flattened = Flatten()(pool3)


dense1 = Dense(128, activation='relu')(flattened)

# Add the dense layer
dense2 = Dense(1, activation='sigmoid')(dense1)

# Create the model
model = Model(inputs=inputs, outputs=dense2)

# Compile the model
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='SGD', metrics=['accuracy'])

# Print the model summary
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1998, 101, 1)]    0         
                                                                 
 conv2d (Conv2D)             (None, 1996, 99, 16)      160       
                                                                 
 max_pooling2d (MaxPooling2  (None, 998, 49, 16)       0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 995, 46, 32)       8224      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 331, 15, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 328, 12, 64)       32832 

In [16]:
np.where(np.isinf(real['x']) == True)

(array([  2,   2,   2, ..., 749, 749, 749]),
 array([728, 732, 732, ..., 423, 423, 428]),
 array([2, 1, 2, ..., 2, 3, 3]))

In [20]:
# prompt: train the model on real['x'] and fake['x] with the labels being 1 for real and 0 for fake

import numpy as np
# Prepare the training data
value = 65470.0

real_x = real['x']
fake_x = fake['x']

real_x = np.nan_to_num(real_x, value)
fake_x = np.nan_to_num(fake_x, value)


# Prepare the training labels
real_y = np.ones((real_x.shape[0], 1))
fake_y = np.zeros((fake_x.shape[0], 1))




In [21]:
# prompt: standardize the datasets

import numpy as np
# Standardize the real and fake datasets
mean_real = np.mean(real_x, axis=0)
print(mean_real)
std_real = np.std(real_x, axis=0)
print(std_real)
real_x = (real_x - mean_real) / std_real

mean_fake = np.mean(fake_x, axis=0)
std_fake = np.std(fake_x, axis=0)
fake_x = (fake_x - mean_fake) / std_fake


[[4.4617e-02 6.1066e-02 2.7023e-02 ... 4.0174e-05 1.1456e-04 9.5367e-05]
 [5.8228e-02 1.4014e-01 4.8126e-02 ... 1.4734e-04 2.4116e-04 1.0449e-04]
 [4.8332e-03 1.9318e-02 1.9379e-02 ... 8.1658e-06 3.4511e-05 3.5226e-05]
 ...
 [9.1003e-02 3.9990e-01 3.3228e-01 ... 3.1471e-05 4.0948e-05 4.5598e-05]
 [2.6318e-01 1.9910e-01 3.8574e-01 ... 2.3603e-05 4.0174e-05 4.7565e-05]
 [2.1973e-02 5.3467e-02 8.9050e-02 ... 3.0935e-05 5.4240e-05 5.0306e-05]]


/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:152: RuntimeWarning: overflow encountered in reduce
  arrmean = umr_sum(arr, axis, dtype, keepdims=True, where=where)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:176: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:187: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims=keepdims, where=where)


[[8.647e-01 1.178e+00 5.259e-01 ... 8.459e-04 2.630e-03 2.264e-03]
 [1.575e+00 3.611e+00 1.249e+00 ... 4.005e-03 6.126e-03 2.197e-03]
 [8.881e-02 3.640e-01 4.697e-01 ... 0.000e+00 6.461e-04 6.905e-04]
 ...
 [2.312e-01 1.079e+00 8.184e-01 ... 0.000e+00 0.000e+00 0.000e+00]
 [7.598e-01 5.767e-01 1.128e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.180e-02 1.128e-01 1.812e-01 ... 0.000e+00 0.000e+00 0.000e+00]]


<ipython-input-21-56a831b1df9b>:9: RuntimeWarning: divide by zero encountered in divide
  real_x = (real_x - mean_real) / std_real
<ipython-input-21-56a831b1df9b>:9: RuntimeWarning: invalid value encountered in divide
  real_x = (real_x - mean_real) / std_real
<ipython-input-21-56a831b1df9b>:13: RuntimeWarning: divide by zero encountered in divide
  fake_x = (fake_x - mean_fake) / std_fake
<ipython-input-21-56a831b1df9b>:13: RuntimeWarning: invalid value encountered in divide
  fake_x = (fake_x - mean_fake) / std_fake


In [22]:
real_x[0][0]

array([-0.0516 , -0.05185, -0.0514 , -0.05118, -0.0517 , -0.03766,
       -0.0381 , -0.0377 , -0.03748, -0.03754, -0.03665, -0.05182,
       -0.04968, -0.04916, -0.05084, -0.04565, -0.0437 , -0.04102,
       -0.03848, -0.04147, -0.03683, -0.03714, -0.03748, -0.0371 ,
       -0.04373, -0.03793, -0.0453 , -0.0427 , -0.0369 , -0.03827,
       -0.04022, -0.03995, -0.05127, -0.05045, -0.03857, -0.04242,
       -0.0431 , -0.0453 , -0.05127, -0.04108, -0.04013, -0.03677,
       -0.04166, -0.0451 , -0.05078, -0.05072, -0.05035, -0.0394 ,
       -0.04163, -0.0603 , -0.04303, -0.03723, -0.0455 , -0.0515 ,
       -0.04007, -0.04156, -0.04422, -0.046  , -0.0403 , -0.03925,
       -0.0429 , -0.03888, -0.0387 , -0.0397 , -0.03897, -0.04178,
       -0.03842, -0.0487 , -0.051  , -0.05176, -0.0516 , -0.045  ,
       -0.04788, -0.05176, -0.0476 , -0.0512 , -0.04913, -0.04944,
       -0.05063, -0.05014, -0.04974, -0.05063, -0.05017, -0.04233,
       -0.04144, -0.0489 , -0.05066, -0.0441 , -0.0513 , -0.04

In [12]:
import numpy as np

# Create a numpy array
arr2 = real_x

# Find the maximum value
max_value = np.max(arr2)
print(max_value)

# Replace the maximum value with negative infinity
arr2[arr2 == max_value] = -np.inf

# Find the second maximum value
second_max_value = np.max(arr2)

# print("Original array:", arr2)
print("Second maximum value:", second_max_value)


nan
Second maximum value: nan


In [23]:
# prompt: train the model on real['x'] and fake['x] with the labels being 1 for real and 0 for fake

import numpy as np
# Prepare the training data
value = 0

real_x = np.nan_to_num(real_x, value)
fake_x = np.nan_to_num(fake_x, value)


# Prepare the training labels
real_y = np.ones((real_x.shape[0], 1))
fake_y = np.zeros((fake_x.shape[0], 1))




In [24]:
print(real_x[5][4])

[-5.685e-02 -4.166e-02 -3.860e-02 -3.769e-02 -3.760e-02 -3.668e-02
 -3.870e-02 -3.775e-02 -4.706e-02 -4.062e-02 -3.812e-02 -3.964e-02
 -4.895e-02 -3.918e-02 -4.285e-02 -4.199e-02 -4.147e-02 -4.056e-02
 -4.102e-02 -3.815e-02 -3.683e-02 -3.680e-02 -3.687e-02 -3.680e-02
 -3.708e-02 -3.674e-02 -3.665e-02 -3.772e-02 -3.775e-02 -4.114e-02
 -3.821e-02 -3.979e-02 -4.587e-02 -4.034e-02 -3.839e-02 -3.809e-02
 -4.327e-02 -3.729e-02 -3.766e-02 -3.854e-02 -3.836e-02 -3.790e-02
 -5.283e-02 -4.947e-02 -4.980e-02 -4.092e-02 -3.888e-02 -3.821e-02
 -4.486e-02 -5.219e-02 -5.423e-02 -5.148e-02 -3.879e-02 -4.089e-02
 -5.380e-02 -3.897e-02 -4.214e-02 -4.706e-02 -5.377e-02 -5.185e-02
 -5.127e-02 -5.203e-02 -4.297e-02 -3.857e-02 -6.550e+04 -3.778e-02
 -3.955e-02 -4.395e-02 -6.550e+04 -4.086e-02 -4.395e-02 -5.341e-02
 -5.249e-02 -5.048e-02 -5.310e-02 -4.385e-02 -4.880e-02 -5.737e-02
 -5.087e-02 -4.504e-02 -3.802e-02 -4.056e-02 -4.749e-02 -6.550e+04
 -5.542e-02 -4.935e-02 -6.750e-02 -8.545e-02 -5.142e-02 -4.745

In [25]:
# prompt: split the dataset using real_x, fake_x, real_y, fake_y

import numpy as np
# Split the dataset into training and test sets
from sklearn.model_selection import train_test_split

real_x_train, real_x_test, real_y_train, real_y_test = train_test_split(real_x, real_y, test_size=0.2)
fake_x_train, fake_x_test, fake_y_train, fake_y_test = train_test_split(fake_x, fake_y, test_size=0.2)

# Combine the training data
x_train = np.concatenate((real_x_train, fake_x_train))
y_train = np.concatenate((real_y_train, fake_y_train))

# Combine the test data
x_test = np.concatenate((real_x_test, fake_x_test))
y_test = np.concatenate((real_y_test, fake_y_test))


In [26]:
np.where(np.isinf(x_train) == True)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [27]:
# Combine the real and fake data
x_train = np.concatenate((real_x, fake_x), axis=0)
y_train = np.concatenate((real_y, fake_y), axis=0)

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
47/47 [==============================] - 13s 126ms/step - loss: nan - accuracy: 0.5040
Epoch 2/10
47/47 [==============================] - 4s 78ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 3/10
47/47 [==============================] - 4s 78ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 4/10
47/47 [==============================] - 4s 76ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 5/10
47/47 [==============================] - 4s 76ms/step - loss: 0.6932 - accuracy: 0.4813
Epoch 6/10
47/47 [==============================] - 4s 80ms/step - loss: 0.6932 - accuracy: 0.4880
Epoch 7/10
47/47 [==============================] - 4s 77ms/step - loss: 0.6932 - accuracy: 0.4867
Epoch 8/10
47/47 [==============================] - 4s 77ms/step - loss: 0.6932 - accuracy: 0.4827
Epoch 9/10
47/47 [==============================] - 4s 77ms/step - loss: 0.6932 - accuracy: 0.4840
Epoch 10/10
47/47 [==============================] - 4s 80ms/step - loss: 0.6932 - accuracy: 0.4667


In [ ]:
# prompt: create a new reshaped X_train that is 2D (name it xgboost_x_train)

xgboost_x_train = x_train.reshape((x_train.shape[0], x_train.shape[1] * x_train.shape[2]))


In [ ]:
# prompt: create an XGBoost classifier for real_x and fake_x

import numpy as np
from xgboost import XGBClassifier

# Create the XGBoost classifier
xgb_classifier = XGBClassifier()

# Train the XGBoost classifier on the real and fake data
xgb_classifier.fit(xgboost_x_train, y_train)


In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

In [ ]:
# prompt: use torch.Dataloader on x_train, x_test, y_train, y_test

train_dataset = torch.utils.data.TensorDataset(torch.from_numpy(x_train), torch.from_numpy(y_train))
test_dataset = torch.utils.data.TensorDataset(torch.from_numpy(x_test), torch.from_numpy(y_test))

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=16, shuffle=False)


In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 4

trainset =
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [ ]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(16, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(10912 , 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [ ]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        # zero the parameter gradients
        optimizer.zero_grad()
        input_tensor = inputs.to(dtype=torch.float)
        labels = labels.squeeze().long()

        # forward + backward + optimize
        outputs = net(input_tensor)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

print('Finished Training')

RuntimeError: Given groups=1, weight of size [6, 16, 5, 5], expected input[1, 12, 1998, 101] to have 16 channels, but got 12 channels instead

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score
from sklearn.ensemble import GradientBoostingClassifier

# Convert the data to a flat 2D shape
X_train_flat = x_train.reshape(x_train.shape[0], -1)
X_test_flat = x_test.reshape(x_test.shape[0], -1)

# Create Gradient Boosting classifier
model = GradientBoostingClassifier(random_state=42, verbose=True)
# Train the model
model.fit(X_train_flat, y_train.ravel())

# Make predictions
y_pred = model.predict(X_test_flat)

# Calculate accuracy and F1 score
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("&quot;Accuracy: {:.4f}&quot;".format(accuracy))
print("&quot;F1 score: {:.4f}&quot;".format(f1))


      Iter       Train Loss   Remaining Time 
         1           1.1963           28.85m
         2           1.0407           28.32m
         3           0.9109           34.95m
         4           0.8012           32.74m
         5           0.7075           35.74m
         6           0.6268           37.69m
         7           0.5568           38.33m
         8           0.4957           38.81m
         9           0.4422           39.26m
        10           0.3951           38.07m
        20           0.1355           31.41m


KeyboardInterrupt: 

In [ ]:
np.max(real['x'])

inf

In [ ]:
arr = np.array(real['x'])
indices = np.where(np.isinf(arr))
print("Infinite values:", indices)


Infinite values: (array([  2,   2,   2, ..., 749, 749, 749]), array([728, 732, 732, ..., 423, 423, 428]), array([2, 1, 2, ..., 2, 3, 3]))


In [ ]:
arr[2][728]

array([2.3680e+04, 3.2576e+04,        inf, 5.0848e+04, 4.3280e+03,
       1.6288e+02, 1.0450e+02, 8.6188e+01, 1.9094e+01, 1.2742e+01,
       1.5025e+02, 9.2400e+02, 1.4210e+03, 4.8675e+02, 1.8156e+01,
       1.2050e+02, 3.2650e+02, 5.8550e+02, 5.1100e+02, 1.3300e+02,
       5.0812e+01, 5.6156e+01, 2.0662e+02, 4.0025e+02, 5.9500e+02,
       9.9300e+02, 9.2450e+02, 4.4375e+02, 6.4625e+01, 1.8016e+01,
       3.2844e+01, 6.0281e+01, 5.4188e+01, 6.5062e+01, 1.4047e+01,
       6.5391e+00, 4.2688e+01, 7.7000e+01, 1.9594e+01, 1.9873e-01,
       2.4648e+00, 1.8496e+00, 3.0312e+00, 7.0264e-01, 1.3574e+00,
       1.4180e+00, 9.9170e-01, 4.6143e-01, 1.8398e+00, 3.6367e+00,
       4.3384e-01, 8.7939e-01, 2.3652e+00, 1.1475e+00, 5.1562e+00,
       1.6904e+00, 1.0068e+00, 7.1973e-01, 2.0972e-01, 1.1563e-05,
       1.9019e-01, 2.1692e-01, 2.2949e-01, 7.1472e-02, 6.5491e-02,
       3.0005e-01, 2.0728e-01, 1.1279e-01, 4.5319e-02, 3.1860e-01,
       3.4375e-01, 2.8735e-01, 3.8794e-01, 5.9277e-01, 2.9388e

In [ ]:
value = 65470.0

x_train[np.isinf(x_train)] = np.nan  # Replace infinite with NaN
x_train = np.nan_to_num(x_train, value)


In [ ]:
import numpy as np

# Create a numpy array
arr2 = np.array(real['x'])

# Find the maximum value
max_value = np.max(arr2)

# Replace the maximum value with negative infinity
arr2[arr2 == max_value] = -np.inf

# Find the second maximum value
second_max_value = np.max(arr2)

# print("Original array:", arr2)
print("Second maximum value:", second_max_value)


Second maximum value: 65470.0
